### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by Lylo01** [B34STW4RS/AD-Evo-Tuner#14]
Hi,

Thank you so much for your work on this! I am running into an error message, any help would be really appreciated:
```
E:\Apps\AD-Evo-Tuner>python ez-adt_v0.py
Traceback (most recent call last):
  File "E:\Apps\AD-Evo-Tuner\train.py", line 11, in <module>
    import torch
  File "C:\Users\XY\anaconda3\envs\adt\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\XY\anaconda3\envs\adt\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
```
OS: Win 10x64
Conda installed, also ran
`conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
`nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

**Comment by B34STW4RS** [comment]
> Hi,
> 
> Thank you so much for your work on this! I am running into an error message, any help would be really appreciated:
> 
> ```
> E:\Apps\AD-Evo-Tuner>python ez-adt_v0.py
> Traceback (most recent call last):
>   File "E:\Apps\AD-Evo-Tuner\train.py", line 11, in <module>
>     import torch
>   File "C:\Users\XY\anaconda3\envs\adt\lib\site-packages\torch\__init__.py", line 128, in <module>
>     raise err
> OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\XY\anaconda3\envs\adt\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
> ```
> 
> OS: Win 10x64 Conda installed, also ran `conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia ` nvcc --version
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2023 NVIDIA Corporation
> Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
> Cuda compilation tools, release 12.1, V12.1.66
> Build cuda_12.1.r12.1/compiler.32415258_0
> ```

sorry been busy with some real life stuff, I modified the environment slightly, lemme know if its still an issue. I'm currently working to restart this project from a new code base so expect major changes within the next month.
